### ISSUE TITLE
 cant find zbar.h module

### ISSUE THREAD

**Issue by bestaps** [npinchot/zbar#2]
In file included from zbarmodule.c:24:0:
zbarmodule.h:26:18: fatal error: zbar.h: No such file or directory
 #include <zbar.h>

**Comment by npinchot** [comment]
Sorry I missed this back when you added it 😞 Not sure how I can help on this one. I didn't write zbar, I just forked it. I don't recall why. If you still need help on this one, check the official page over at http://zbar.sourceforge.net
